-- AlterTable
ALTER TABLE "Circuit" ADD COLUMN     "cosPhi" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "simultaneityFactor" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "utilizationFactor" DOUBLE PRECISION NOT NULL DEFAULT 1;
